hide cookie banner
sakusaku3939/DeepLAndroid pull request #2
Opened 2020-11-15 16:16 UTC by fm-sys

I saw in the code that there was a workaround to hide the cookie banner using `cookieManager` but it wasn't working (at least not at my device/geolocation) so I replaced that part with JavaScript.

Since it's probably best to keep the code all together at the same location, I created this pull request containing the fix...

2020-11-16 05:03 UTC, sakusaku3939 requested changes
Thanks for your pull request, good suggestions!
However, since it didn't work in my environment, I would appreciate it if you could change `.dl_cookieBanner_container` to `#dl_cookieBanner`.

2020-11-16 14:50 UTC, fm-sys commented
I changed my language in the device settings to Japanese (hopefully I find the right button to change it back 😅) and now can reproduce the problem. Looks like the deepl website has different structures depending on the user language. So I will try to find a cross language solution...

2020-11-16 20:19 UTC, fm-sys commented on app/src/main/java/com/example/deeplviewer/MainActivity.kt
> +                            "\$('.dl_cookieBanner_container').hide();" +
Done! Let's see if it works for you too...
If not, we can also keep the `cookieManager`-implementation as a fallback (I guess this one was working for you?)

2020-11-17 13:55 UTC, sakusaku3939 commented
That makes sense... Thanks for doing the research.
For now I'll merge this pull request for now. Thank you!

2020-11-17 13:55 UTC, merged