add Dark Theme support
sakusaku3939/DeepLAndroid pull request #28
Opened 2021-07-21 10:57 UTC by S-H-Y-A

Fixes #17
Please take a look at the pictures.

![Screenshot_20210721-195122783](https://user-images.githubusercontent.com/74596628/126477569-ae523507-cbe9-4f45-97c2-b651ccb5d053.jpg)
![Screenshot_20210721-195142716](https://user-images.githubusercontent.com/74596628/126477572-5dc47cb6-c247-4547-b10d-08854bb4e8ca.jpg)

2021-07-23 07:56 UTC, sakusaku3939 commented
Thanks for the good work!
Basically it seems to be working fine, but the app is crashing when certain actions are performed, so please fix this.

2021-07-23 07:58 UTC, sakusaku3939 requested changes
Thanks for the good work!
Basically it seems to be working fine, but the app is crashing when certain actions are performed, so please fix this.

2021-07-23 07:58 UTC, sakusaku3939 commented on app/src/main/java/com/example/deeplviewer/MainActivity.kt
> +                ?.substring(startUrl.length))
Throws `java.lang.StringIndexOutOfBoundsException` if `onSaveInstanceState` is called after all characters have been deleted

Examples
1) Input a character
2) Delete all characters
3) Switching themes

My guess is that the "#ja/en/" parameter is lost when the input field is empty, so you have specified an index out of bounds.

2021-07-23 10:13 UTC, S-H-Y-A commented on app/src/main/java/com/example/deeplviewer/MainActivity.kt
> +                ?.substring(startUrl.length))
I changed to compare webView url length and default url length to solve this problem.

2021-07-23 16:59 UTC, merged

2021-07-23 17:02 UTC, sakusaku3939 commented
Seems to be no problem!
Lastly, I'll make some corrections on my end so that the splash screen logo and the connection failure screen logo will also change to match the dark mode.

Screenshot:
![Screenshot_20210724-012115](https://user-images.githubusercontent.com/53967490/126816398-73ce1f3c-2276-4f1b-9bf7-354a48c4a4d1.png)

2021-07-24 09:17 UTC, adarsh1001 commented
Thanks for this! @S-H-Y-A @sakusaku3939  one small suggestion would be to color the top status bar as well so that it blends with the dark mode (like other apps do).

Google Translate Dark Mode:
![Screenshot_20210724-144000_(1).png](https://user-images.githubusercontent.com/8820038/126863905-ca355009-6291-4fee-bb10-2b9df85cb910.png)

Current DeepL Dark Mode:
![Screenshot_20210724-143954_(1).png](https://user-images.githubusercontent.com/8820038/126863942-1d861cb2-b5e0-4e8d-b164-7e960f794802.png)