Add SettingsActivity
sakusaku3939/DeepLAndroid pull request #37
Opened 2021-08-28 16:44 UTC by S-H-Y-A

Add SettingsActivity to set default app theme.

![Screenshot_20210829-011106](https://user-images.githubusercontent.com/74596628/131224859-756ca494-64f0-47b6-b871-967ef14ffac5.png)

2021-08-29 07:56 UTC, sakusaku3939 reviewed
Please check because the app crashed when I launched it.
If I can't reproduce it, I'll report back with more details.

2021-08-29 07:56 UTC, sakusaku3939 commented on app/src/main/java/com/example/deeplviewer/App.kt
> +            config.getString("darkMode", AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM.toString())!!
A casting error has occurred.
`java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String`

2021-08-29 08:23 UTC, fm-sys commented on app/src/main/java/com/example/deeplviewer/App.kt
> +            config.getString("darkMode", AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM.toString())!!
I have a Idea what the problem could be:
The same preference key was used before to store a boolean. If the preference was set, the app will crash. So either we need to catch the exception or use a different preference key for the string value, 
E.g. `themeMode`

```
private fun switchTheme() {
        val config = getSharedPreferences("config", Context.MODE_PRIVATE)
        when (intent?.getStringExtra("switchTheme")) {
            "light" -> config.edit().putBoolean("darkMode", false).apply()
            "dark" -> config.edit().putBoolean("darkMode", true).apply()
            else -> {}
        }
        if (config.getBoolean("darkMode", false)) {
            AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
        }
    }

2021-08-29 11:49 UTC, fm-sys commented
LGTM now 👍

Optional: move key into a non translatable string resource so there's only one place where it is defined.

2021-08-29 18:54 UTC, S-H-Y-A commented
I added language switch button option.
Please check it, too.

![Screenshot_20210830-035157699.jpg](https://user-images.githubusercontent.com/74596628/131262107-f31d79ec-2a09-4a10-b216-f3667b43403c.jpg)

2021-08-30 03:59 UTC, sakusaku3939 requested changes
Excellent work!
The settings screen looks fine, but there seems to be a flaw in the app shortcut, so please fix it at the end.

2021-08-30 03:59 UTC, sakusaku3939 commented on app/src/main/java/com/example/deeplviewer/MainActivity.kt
> -    private fun setThemeSwitchShortcut() {
If you update from a device with v5.0 installed, the "dark mode" set by the dynamic shortcut will remain, so it would be good to include a process to reset it.

<img src="https://user-images.githubusercontent.com/53967490/131281384-fc5cb1e4-4afe-49b2-a256-b138d3b4df11.png" width="400">

2021-08-30 03:59 UTC, sakusaku3939 commented on app/src/main/res/drawable/ic_baseline_settings_24.xml
> +        android:fillColor="@android:color/white"
The fill color is set to white, so it seems to be covering the background color.
|                                                                                                                                 |                                                                                                                                 | 
| ------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------- | 
| ![Screenshot_1630294884](https://user-images.githubusercontent.com/53967490/131281984-421d9569-8598-4147-a9e9-ca951b18e92d.png) | ![Screenshot_1630292903](https://user-images.githubusercontent.com/53967490/131281989-4d894d5d-8af4-48dd-8254-ca1a67205b10.png) |

2021-08-30 05:27 UTC, sakusaku3939 commented on app/src/main/res/drawable/ic_baseline_settings_24.xml
> +        android:fillColor="@android:color/white"
@S-H-Y-A This may be a small detail, but the Material Design Guidelines recommend 87% opacity (#000000) = #DE000000 for active icons, so if you don't mind, I'd appreciate it if you could darken the color a bit!

Reference : 
https://material.io/design/iconography/system-icons.html#color

2021-08-30 06:32 UTC, merged

2021-08-30 06:40 UTC, sakusaku3939 commented
It seems to be no problem.:+1:
I know this was a lot of work, thank you!